# File: fly.toml
app = "rederive-api"
primary_region = "lhr"
[build]
[mounts]
  source = "rederive_data"
  destination = "/data"
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1
